config/routes.rb
Rails.application.routes.draw do
  resources :drawings
  resources :branches
  resources :sketches
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
	  root :to => "sketches#index"
  end

  root 'static_pages#home'
  get 'static_pages/home'
  get '/', to: 'static_pages#home'
  post '/drawings/canvas', to: 'drawings#canvas'
  post '/drawings/merge', to: 'drawings#merge'
end

app/models/sketch.rb
class Sketch < ApplicationRecord
	belongs_to :user
	has_many :branches
	has_many :drawings
	validates :description, presence: true, length: { maximum: 140 }
	validates :title, presence: true, length: { maximum: 60 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sketches
end

app/controllers/sketches_controller.rb
class SketchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sketch, only: [:show, :edit, :update, :destroy]

  # GET /sketches
  # GET /sketches.json
  def index
    @sketches = Sketch.all
  end

  # GET /sketches/1
  # GET /sketches/1.json
  def show
    @sketch = Sketch.find(params[:id])
    Rails.logger.debug(@sketch.branches.collect(&:id))
    Rails.logger.debug(@sketch.drawings.collect(&:branch_id))
    # Rails.logger.debug(@sketch.drawings.collect(&:data_url))
  end

  # GET /sketches/new
  def new
    @sketch = current_user.sketches.build
  end

  # GET /sketches/1/edit
  def edit
  end

  # POST /sketches
  # POST /sketches.json
  def create
    sketch_params[:data_url] = "default"
    sketch_params[:user_id] = current_user.id
    Rails.logger.debug("NEW SKETCH PARAMS")
    Rails.logger.debug(sketch_params)
    @sketch = current_user.sketches.build(sketch_params)

    respond_to do |format|
      if @sketch.save
        format.html { redirect_to @sketch, notice: 'Sketch was successfully created.' }
        format.json { render :show, status: :created, location: @sketch }
      else
        format.html { render :new }
        format.json { render json: @sketch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sketches/1
  # PATCH/PUT /sketches/1.json
  def update
    respond_to do |format|
      if @sketch.update(sketch_params)
        format.html { redirect_to @sketch, notice: 'Sketch was successfully updated.' }
        format.json { render :show, status: :ok, location: @sketch }
      else
        format.html { render :edit }
        format.json { render json: @sketch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sketches/1
  # DELETE /sketches/1.json
  def destroy
    @sketch.destroy
    respond_to do |format|
      format.html { redirect_to sketches_url, notice: 'Sketch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sketch
      @sketch = Sketch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sketch_params
      params.require(:sketch).permit(:title, :description, :data_url)
    end
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/views/sketches/_form.html.erb
<%= form_with(model: sketch, local: true) do |form| %>
  <% if sketch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sketch.errors.count, "error") %> prohibited this sketch from being saved:</h2>

      <ul>
      <% sketch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title, id: :sketch_title, autocomplete: "off", :size => 40 %>
  </div>

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description, id: :sketch_description, cols: "40", rows: "4" %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'button' %>
  </div>
<% end %>

app/views/sketches/edit.html.erb
<h1>Editing Sketch</h1>

<%= render 'form', sketch: @sketch %>

<%= link_to 'Show', @sketch %> |
<%= link_to 'Back', sketches_path %>

app/views/sketches/index.html.erb
<!DOCTYPE html>
<html>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>
  <body>
      <%= javascript_pack_tag 'application' %>
      <% if user_signed_in? %>
        <%= react_component("Sketches", {username: current_user.name, user_id: current_user.id, sketch_count: current_user.sketches.count, sketch_ids: current_user.sketches.collect(&:id), sketch_titles: current_user.sketches.collect(&:title), sketch_descriptions: current_user.sketches.collect(&:description), sketch_images: current_user.sketches.collect(&:data_url)}) %>
      <% else %>
        <%= react_component("Home") %>
      <% end %>
    </body>
</html>

app/views/sketches/new.html.erb
<!DOCTYPE html>
<html>
	<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  	<link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>
  	<body>
  		<%= javascript_pack_tag 'application' %>
		<% if user_signed_in? %>
			<%= react_component("NavBar", {username: current_user.name}) %>
			<div class="form-container">
				<h1>New Sketch</h1>
		        <%= render 'form', sketch: @sketch %>
	    	</div>
	    <% else %>
	        <%= react_component("Home") %>
	    <% end %>
	</body>
</html>

app/views/sketches/show.html.erb
<!DOCTYPE html>
<html>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>
  <body>
      <%= javascript_pack_tag 'application' %>
      <% if user_signed_in? %>
        <%= react_component("SketchHome", {username: current_user.name, sketch_id: @sketch.id, sketch_title: @sketch.title, sketch_description: @sketch.description, branch_count: @sketch.branches.count, branch_ids: @sketch.branches.collect(&:id), drawing_branch_ids: @sketch.drawings.collect(&:branch_id), drawing_urls: @sketch.drawings.collect(&:data_url)}) %>
      <% else %>
        <%= react_component("Home") %>
      <% end %>
    </body>
</html>