config/routes.rb
Rails.application.routes.draw do
  resources :drawings
  resources :branches
  resources :sketches
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
	  root :to => "sketches#index"
  end

  root 'static_pages#home'
  get 'static_pages/home'
  get '/', to: 'static_pages#home'
  post '/drawings/canvas', to: 'drawings#canvas'
  post '/drawings/merge', to: 'drawings#merge'
end

app/models/drawing.rb
class Drawing < ApplicationRecord
	belongs_to :branch
	belongs_to :sketch
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_drawing, only: [:show, :edit, :update, :destroy]

  # GET /drawings
  # GET /drawings.json
  def index
    @drawings = Drawing.all
  end

  # GET /drawings/1
  # GET /drawings/1.json
  def show
  end

  # POST /drawings/canvas
  def canvas
    $sketch_id = canvas_params[:sketch_id]
    @sketch = Sketch.find($sketch_id)
    if @sketch.branches.count == 0
      @master_branch = Branch.new(sketch_id: $sketch_id)
      @master_branch.save
      $branch_id = @master_branch.id
    end

    if canvas_params[:new_branch]
      @new_branch = Branch.new(sketch_id: $sketch_id)
      @new_branch.save
      $branch_id = @new_branch.id
    end

    # merging into master
    if canvas_params[:merge_branch]
      Rails.logger.debug("hi sketch branches")
      Rails.logger.debug(@sketch.branches.first.id)

      Rails.logger.debug("master branch last drawing")
      # Rails.logger.debug(@sketch.branches.first.drawings.last.data_url)
      $master_bg = @sketch.branches.first.drawings.last.data_url
      Rails.logger.debug($master_bg)
      $branch_id = @sketch.branches.first.id
    end

    # $branch_id = @master_branch.id

    # Rails.logger.debug($branch_id)
    $canvas_bg = canvas_params[:canvas_bg]
  end

  # POST /drawings/merge
  def merge
    @drawing = Drawing.new(drawing_params)
    @sketch = Sketch.find(drawing_params[:sketch_id])

    respond_to do |format|
      if @drawing.save
        @sketch.update_attributes(:data_url => drawing_params[:data_url])
        format.html { redirect_to @drawing, notice: 'Drawing was successfully created.' }
        format.json { render :show, status: :created, location: @drawing }
      else
        format.html { render :new }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET /drawings/new
  def new
    @drawing = Drawing.new()
    @sketch_id = $sketch_id
    @canvas_bg = $canvas_bg
    @branch_id = $branch_id
    @master_bg = $master_bg

    Rails.logger.debug("master branch new url") 
    Rails.logger.debug(@master_bg)

    if @master_bg
      @merge = true
      Rails.logger.debug("merge is true")
    else 
      @merge = false
    end  
  end

  # GET /drawings/1/edit
  def edit
  end

  # POST /drawings
  # POST /drawings.json
  def create
    @drawing = Drawing.new(drawing_params)
    @sketch = Sketch.find(drawing_params[:sketch_id])

    respond_to do |format|
      if @drawing.save
        @sketch.update_attributes(:data_url => drawing_params[:data_url])
        format.html { redirect_to @drawing, notice: 'Drawing was successfully created.' }
        format.json { render :show, status: :created, location: @drawing }
      else
        format.html { render :new }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drawings/1
  # PATCH/PUT /drawings/1.json
  def update
    respond_to do |format|
      if @drawing.update(drawing_params)
        format.html { redirect_to @drawing, notice: 'Drawing was successfully updated.' }
        format.json { render :show, status: :ok, location: @drawing }
      else
        format.html { render :edit }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drawings/1
  # DELETE /drawings/1.json
  def destroy
    @drawing.destroy
    respond_to do |format|
      format.html { redirect_to drawings_url, notice: 'Drawing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drawing
      @drawing = Drawing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drawing_params
      params.require(:drawing).permit(:sketch_id, :branch_id, :data_url)
    end

    def canvas_params
      params.require(:drawing).permit(:new_branch, :merge_branch, :sketch_id, :canvas_bg)
    end
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/views/drawings/_form.html.erb
<%= form_with(model: drawing, local: true) do |form| %>
  <% if drawing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drawing.errors.count, "error") %> prohibited this drawing from being saved:</h2>

      <ul>
      <% drawing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :branch_id %>
    <%= form.number_field :branch_id, id: :drawing_branch_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drawings/edit.html.erb
<h1>Editing Drawing</h1>

<%= render 'form', drawing: @drawing %>

<%= link_to 'Show', @drawing %> |
<%= link_to 'Back', drawings_path %>

app/views/drawings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drawings</h1>

<table>
  <thead>
    <tr>
      <th>Branch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drawings.each do |drawing| %>
      <tr>
        <td><%= drawing.branch_id %></td>
        <td><%= link_to 'Show', drawing %></td>
        <td><%= link_to 'Edit', edit_drawing_path(drawing) %></td>
        <td><%= link_to 'Destroy', drawing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drawing', new_drawing_path %>

app/views/drawings/new.html.erb
<!DOCTYPE html>
<html>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Source Sans Pro' rel='stylesheet'>
  <body>
      <%= javascript_pack_tag 'application' %>
      <% if user_signed_in? %>
        <%= react_component("Canvas", {sketch_id: @sketch_id, branch_id: @branch_id, canvas_bg: @canvas_bg, master_bg: @master_bg, merge: @merge}) %>
      <% else %>
        <%= react_component("Home") %>
      <% end %>
    </body>
</html>

app/views/drawings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Branch:</strong>
  <%= @drawing.branch_id %>
</p>

<%= link_to 'Edit', edit_drawing_path(@drawing) %> |
<%= link_to 'Back', drawings_path %>